language: julia

jobs:
  include:
    - stage: documentation
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
              Pkg.add(PackageSpec(url="https://github.com/arzwa/DiscreteMarkovFit.jl"));
              Pkg.add(PackageSpec(url="https://github.com/arzwa/NewickTree.jl", rev="beluga"));
              Pkg.add(PackageSpec(url="https://github.com/arzwa/AdaptiveMCMC.jl"));
              Pkg.instantiate();
              Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
after_success: skip
